### ISSUE TITLE
Unhandled Exception: type 'AlignmentDirectional' is not a subtype of type 'Alignment' in type cast

### ISSUE THREAD

**Issue by rahulmitta1** [joseph-grabinger/flutter_to_pdf#85]
Got `type 'AlignmentDirectional' is not a subtype of type 'Alignment' in type cast` error when trying to use `ExportDelegate.exportToPdfDocument()`

**STACK TRACE**

```
E/flutter (10299): #0      AlignConverter.toPdfWidget (package:flutter_to_pdf/widgets/align.dart:11:31)
E/flutter (10299): #1      ExportInstance.matchWidget (package:flutter_to_pdf/export_instance.dart:150:16)
E/flutter (10299): <asynchronous suspension>
...........
E/flutter (10299): #118    ExportInstance._visit (package:flutter_to_pdf/export_instance.dart:58:23)
E/flutter (10299): <asynchronous suspension>
E/flutter (10299): #119    ExportInstance.matchWidget (package:flutter_to_pdf/export_instance.dart:292:16)
E/flutter (10299): <asynchronous suspension>
E/flutter (10299): #120    ExportDelegate._exportWidget (package:flutter_to_pdf/export_delegate.dart:109:9)
E/flutter (10299): <asynchronous suspension>
E/flutter (10299): #121    ExportDelegate._exportPage (package:flutter_to_pdf/export_delegate.dart:121:33)
E/flutter (10299): <asynchronous suspension>
E/flutter (10299): #122    ExportDelegate._exportDocument (package:flutter_to_pdf/export_delegate.dart:134:29)
E/flutter (10299): <asynchronous suspension>
E/flutter (10299): #123    ExportDelegate.exportToPdfDocument (package:flutter_to_pdf/export_delegate.dart:57:14)

```

Thanks!

**Comment by joseph-grabinger** [comment]
This issue should be fixed in the newest release (v0.2.2) which is now available on [pub.dev](https://pub.dev/packages/flutter_to_pdf/versions/0.2.2). 

If you still experience any issues feel free to reopen this issue or creating a new one :)
